### ISSUE TITLE
Time-limited whitelist

### ISSUE THREAD

**Issue by Atharex** [anchore/grype#1148]
**What would you like to be added**:
Time-limited whitelists

**Why is this needed**:
To have time management included already with the tool

**Additional context**:

This might be included in the .grype.yaml file, to make it visible and also possible to manage by git.
I'd see it implemented like a check with the system time and breaking the ignore if the time is later than the specified day. (example keyword `valid-until` below)

```
ignore:
  # This is the full set of supported rule fields:
  - vulnerability: CVE-2008-4318
    fix-state: unknown
    valid-until: 03-03-2023      <---- new field for time-limit
    package:
      name: libcurl
      version: 1.5.1
      type: npm
      location: "/usr/local/lib/node_modules/**"
      
```
