### ISSUE TITLE
Grype docker image on dockerhub has no shell commands available to be able to keep it alive for Jenkins exec into scan with it - please add busybox at least

### ISSUE THREAD

**Issue by HariSekhon** [anchore/grype#1287]
**What happened**:

I'm running Jenkins on Kubernetes and am trying to include the grype docker image into the jenkins pod, for which I usually use a simple command like `cat` to keep the docker container alive so that Jenkins pipelines can exec into the container and run the command to do a scan or build or whatever.

I've found that the grype docker image is so stripped down, it doesn't even have busybox to be able to do this.

I've used this pattern successfully with Trivy before (the Trivy docker image contains busybox) and am now trying to do exactly the same thing with Grype:

```yaml
    # https://hub.docker.com/r/anchore/grype
    - name: grype
      #image: anchore/grype:v0.61.1
      image: anchore/grype:latest
      imagePullPolicy: Always
      command:
        - cat
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375  # XXX: needs the docker dind container near the top
      tty: true
      resources:
        requests:
          cpu: 300m
          memory: 300Mi
        limits:
          cpu: '1'
          memory: 1Gi
```

My production pod yaml looks very similar to this:

https://github.com/HariSekhon/Kubernetes-configs/blob/master/jenkins/base/jenkins-agent-pod.yaml

**What you expected to happen**:

I expected the cat command to succeed and keep the container alive so that Jenkins could exec into it to run a scan.

**How to reproduce it (as minimally and precisely as possible)**:

```shell
$ docker run -ti --entrypoint cat anchore/grype 
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "cat": executable file not found in $PATH: unknown.
```

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:
- OS (e.g: `cat /etc/os-release` or similar):

```shell
$ docker run -ti anchore/grype version
Application:          grype
Version:              0.61.1
Syft Version:         v0.79.0
BuildDate:            2023-04-21T17:11:07Z
GitCommit:            3caabc87114a3e0cbfbac7770989bc81e2f5a957
GitDescription:       v0.61.1
Platform:             linux/amd64
GoVersion:            go1.19.8
Compiler:             gc
Supported DB Schema:  5
```
