### ISSUE TITLE
grype cannot scan a local image that was not archived by tar or pushed to a registry

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [anchore/grype#1314]
I have the following pipeline in Tekton:

```
  params:
    - name: IMAGE
    - name: BASE_IMAGE_TRIVY
      type: string
      default: "aquasec/trivy:0.41.0"
    - name: BASE_IMAGE_GRYPE
      type: string
      default: "anchore/grype:v0.62.1-debug"
    - name: PATH_CONTEXT
      description: The build context.
      default: "."
  steps:
    - name: trivy
      image: $(params.BASE_IMAGE_TRIVY)
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
      script: |
        #!/usr/bin/env sh
        set -ex

        trivy image $(params.IMAGE)

    - name: grype
      image: $(params.BASE_IMAGE_GRYPE)
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
      script: |
        #!/busybox/sh
        set -ex

        /grype $(params.IMAGE)
```

Trivy manages to scan the image built with Kaniko, while `grype` causes an error (it does not find this image locally and tries to pull it from remote):

```
+ /grype some_aws_image:latest
1 error occurred:
	* failed to catalog: could not fetch image "some_aws_image:latest": unable to use OciRegistry source: failed to get image descriptor from registry: GET https://some_aws_image_link: unexpected status code 401 Unauthorized: Not Authorized
```

I also tried `grype` locally. Although, when I install this until via brew, it works alright and can scan images present on the machine. But I cannot scan local images with the `grype` docker container. The option `--volume /var/run/docker.sock:/var/run/docker.sock` does not help.
