### ISSUE TITLE
grype explain

### ISSUE THREAD

**Issue by spiffcs** [anchore/grype#1342]
**What would you like to be added**:
During community meetings we've regularly seen the ask for more context for single items in a `grype` command.

The initial discussion has been around adding a command akin to `grype explain`.

There are a couple of forms this command could take.  This issue is a good place to discuss where we want the inital implementation to land.

Ive laid out some options below - these are not exhaustive and we should iterate on this list to find the correct shape
```
grype explain alpine:latest <package-name>
grype alpine:latest --explain <package-name>
grype explain <grype.json> --package <package-name>
grype explain <package-name> --report <grype.json>
```

**Why is this needed**:
Users attempting to remediate supply chain vulnerabilities would benefit by seeing as much info as is available without having to consult the json output. They can understand the What/Where/How to remediate from a single command and it's output.

This include fields from `matchDetails` or location/upstream feilds from the `artifact` portion of the JSON

**Comment by gh-greg** [comment]
**Why is this needed:**
Users attempting to remediate supply chain vulnerabilitiers  would benefit by seeing as much info as is available, for them to understand **What/Where/How**  , to remediate.
-- Thank you for your consideration.

**Comment by willmurphyscode** [comment]
Two other experiences I've been thinking about:


Asking grype to explain a particular CVE:
```
grype some-image:some-tag --explain CVE-1234-1234
```

Asking grype to explain all CVEs above a threshold, or of particular severities:
```
grype some-image:some-tag --explain-by-severity High,Critical
```

Since I imagine two common use cases are, "why'd my image get flagged for CVE-1234-1234?" and "We need to understand and remediate anything higher than medium severity."

I'm also very interested to hear what people think should be in the output of this command. Maybe by default human-readable text that lays out the `matchDetails` in a useful way?

**Comment by wagoodman** [comment]
I also wanted to throw in some thoughts I had as well as thoughts from others in various conversations about this.

Let's assume that https://github.com/anchore/grype/issues/648 is implemented (multiple `-o` output like with syft)
```
$ grype alpine:3.2 -o json=./reports/vulns.json -o table
 ✔ Vulnerability DB        [no update available]
 ✔ Loaded image            
 ✔ Parsed image            
 ✔ Cataloged packages      [16 packages]
 ✔ Scanning image...       [108 vulnerabilities]
   ├── 16 critical, 46 high, 40 medium, 6 low, 0 negligible
   └── 2 fixed
NAME          INSTALLED  FIXED-IN   TYPE  VULNERABILITY     SEVERITY 
busybox       1.23.2-r3             apk   CVE-2015-9261     Medium    
busybox       1.23.2-r3             apk   CVE-2016-2147     High      
busybox       1.23.2-r3             apk   CVE-2016-2148     Critical
busybox       1.23.2-r3             apk   CVE-2017-16544    High      
busybox       1.23.2-r3             apk   CVE-2018-1000500  High      
busybox       1.23.2-r3             apk   CVE-2018-1000517  Critical  
busybox       1.23.2-r3             apk   CVE-2018-20679    High      
busybox       1.23.2-r3             apk   CVE-2019-5747     High      
busybox       1.23.2-r3             apk   CVE-2021-42376    Medium       
busybox       1.23.2-r3             apk   CVE-2022-28391    High      
busybox       1.23.2-r3  1.24.2-r1  apk   CVE-2016-6301     High      
libcrypto1.0  1.0.2k-r0             apk   CVE-2017-3735     Medium    
libcrypto1.0  1.0.2k-r0             apk   CVE-2020-1968     Low       
libcrypto1.0  1.0.2k-r0             apk   CVE-2020-1971     Medium    
libcrypto1.0  1.0.2k-r0             apk   CVE-2021-23840    High      
libcrypto1.0  1.0.2k-r0             apk   CVE-2022-1292     Critical  
libcrypto1.0  1.0.2k-r0             apk   CVE-2022-2068     Critical  
libcrypto1.0  1.0.2k-r0             apk   CVE-2022-4304     Medium    
libcrypto1.0  1.0.2k-r0             apk   CVE-2023-0215     High     
...
```

The nice thing about the table output is that it's short and grokkable, however, it just doesn't help when it comes to getting "why" a match was made --this is what the json is for:

```
$ cat./reports/vulns.json | jq '.matches[0].matchDetails'
[
  {
    "type": "cpe-match",
    "matcher": "apk-matcher",
    "searchedBy": {
      "namespace": "nvd:cpe",
      "cpes": [
        "cpe:2.3:a:busybox:busybox:1.23.2-r3:*:*:*:*:*:*:*"
      ]
    },
    "found": {
      "vulnerabilityID": "CVE-2015-9261",
      "versionConstraint": "< 1.27.2 (unknown)",
      "cpes": [
        "cpe:2.3:a:busybox:busybox:*:*:*:*:*:*:*:*"
      ]
    }
  }
]

```

(and if you care more about the "what" was matched against: `...| jq '.matches[0].artifact'` ... or what was matched with: `| jq '.matches[0].vulnerability'`)

I feel that having a separate `explain` command works nicely when you have already done the leg work of getting the results / analyzing the image and just want the results filtered and summarized.

```
$ grype alpine:3.2 -o json=./reports/vulns.json
$ grype explain ./reports/vulns.json ...(some criteria)
```

There is nothing inherently wrong with this:
```
$ grype alpine:3.2 --explain ...
```

But I have a couple notes about this:
- how do you know what CVE you want explained if you haven't seen the results before? This implies the fastest way to filter results is to run the command twice
- Running grype directly against an image takes a while. This is why we recommend an SBOM as input for users that want to scale cheaply. I feel that this falls into a similar category: if you are persisting your grype results, you can always use grype to explain them without paying the analysis or matching cost again.

So I'm not against `grype --explain` but I do think that workflow-wise it makes sense to keep "getting the results" separate from "analyzing the results".

Or, said another way, I feel that `grype --explain` really feels like `grype -o text [--filter ...]` where we have a new `text` representation of all of the matches and optional `--filter`s that can be applied (note: `-o text ` and `--filter` do not exist today).

A separate command also gives a completely separate CLI surface area, uncoupled with any of the scanning (root) command flags.

```
$ grype explain --help
...
Flags:
    --vuln        A specific vulnerability ID to filter down to
    --cve         Any vulnerability that ultimately maps to a CVE
    --package     A specific package or package@version to focus on
    --severity    Explain matches that have the given severity
    --property    Match any field in the grype JSON output
```

This would let you do things like:
```bash
$ grype explain ./vulns.json --vuln CVE-2023-0215
# explain all matches that have the exact vuln ID

$ grype explain ./vulns.json --cve CVE-2023-0215
# explain all matches that are exactly this CVE or are related to it (e.g. we matched the GHSA ID directly)

$ grype explain ./vulns.json --package libpython
# explain all matches against the packages named "libpython"

$ grype explain ./vulns.json --package libpython@3.7
# explain all matches against the packages named "libpython" with a specific version of "3.7"

$ grype explain ./vulns.json --severity high
# explain all matches with a severity of "High"

$ grype explain ./vulns.json --severity high+
# explain all matches with a severity of "High" or "Critical"

$ grype explain ./vulns.json --property ".artifact.metadata.thing==42"
# explain all matches where there is a syft package property of a particular value
```

I've got questions about what it means to combine these flags:

```
$ grype explain ./vulns.json --cve CVE-2023-0215 --package libpython
```

I could interpret this two ways:
- and conjunction: e.g. match must have the CVE CVE-2023-0215 and be named libpython to be explained
- or conjunction:  e.g. match can have either property to be explained

I can see a user wanting either, I'm curious for interactions here that don't necessarily make this mutually exclusive (but also not too much more complicated).

> I'm also very interested to hear what people think should be in the output of this command. Maybe by default human-readable text that lays out the matchDetails in a useful way?

Much of what I focused on here is about "how to specify what to explain". In terms of the output I think there could be some fun paths here. Regarding the match details, I think the explain result should at a minimum show the match details in a useful way. But there might be more opportunities here as well. Some thoughts I have here:

1. I think the default output should be human readable. But should we provide a machine readable format as well?
2. One of the use cases of explain is to help with triaging results. During the triaging what are the common external sources that someone would consult? Can we summarize that here? For instance, if you need to constantly go to the NVD link to get more information, what is that information? I feel like this information would be ideal to include in explain so one can fully explain the result without consulting other material... saving on time.
3. Should there be an "online" component of this? I feel that by default we should explain with the information we have (the report + DB records), but could we additionally gather information online about a reference to enrich the report?

**Comment by willmurphyscode** [comment]
> - how do you know what CVE you want explained if you haven't seen the results before? This implies the fastest way to filter results is to run the command twice

My assumption is that the user is often running grype twice. The first time tells them that there _is_ something they want to explain, and the second time explains it.

> - Running grype directly against an image takes a while. This is why we recommend an SBOM as input for users that want to scale cheaply. I feel that this falls into a similar category: if you are persisting your grype results, you can always use grype to explain them without paying the analysis or matching cost again.

It seems like there are two workflows here:

1. Re-run grype, but asking it to explain some things. This is slower, but the user didn't have to persist a file or something to prep for it.
2. Run grype on the output of a previous run, or on an SBOM. This is faster, but the user had to persist something ahead of time in order for it to succeed.

I think we should support both workflows. I agree that the first one is slower, but it can be used reactively, which seems important; I suspect users are likely to want to run `explain` if they've been _surprised_, which makes it likely that they haven't saved off an SBOM or vulnerability report.

Are there any objections to supporting both workflows?

**Comment by willmurphyscode** [comment]
@wagoodman and I met about this, and here's where we're leaning:

We will make 3 changes:

1. `--fail-on` will print explanations to stderr at end unless `--quiet` is passed.
2. `grype explain --cve CVE-foo` prints an explanation of CVE-foo to stdout.
3. `grype -o explain` prints an explanation of every CVE to stdout. Implies `--by-cve`

Here's a preliminary draft on what the explanation from `--fail-on` will look like:

```
Failed.
Vulnerabilities at or exceeding severity {{ severity }}:
For CVE-2004-0406 (HIGH):
    matched artifacts:
        package: imagemagick, artifact ID: {{ artifactID }}, version: {{ version }}
            PURL: pkg:deb/debian/imagemagick@8:6.9.11.60+dfsg-1.6?arch=arm64&distro=debian-12
        package: imagemagick-6-common, artifact ID: {{ artifactID }}, version: {{ version }}
            PURL: pkg:deb/debian/imagemagick-6-common@8:6.9.11.60+dfsg-1.6?arch=all&upstream=imagemagick&distro=debian-12
            This CVE is reported against 'imagemagick', the origin of this Debian package.
    URLs:
        - https://security-tracker.debian.org/tracker/CVE-2005-0406 
```

The format for the explanation of a given CVE is still in flux. There may be more info needed in the explanation, but this is enough to start work. I'll work on a draft PR and get some specific feedback about the explanation of particular vulnerabilities.

A good test case here will be to try to triage a false positive based on the output of `grype explain --cve ID`.

**Comment by spiffcs** [comment]
I think this is a great spot for this request:
https://github.com/anchore/grype/issues/1355

If we don't get this at the table view this information would be awesome to have for template/explain areas!

**Comment by wagoodman** [comment]
Some fields that I feel that help during triaging that would be useful in understanding a match:
- cve description: helps understand what the vulnerability is and may go into detail about the artifact that isn't elsewhere
- what location of the artifact this was found
- the CPE searched with and found on the record
- the version range in the vulnerability record that the version of the artifact matched within
- if the CVE was found through another record (e.g. GHSA) including that ID with the package it was found with

Small note: keeping the original namespace the record was found in for each package would be ideal.

Most of these are in the vulnerability match details already. I'm also curious if there is other information that is not in the grype document today that would be useful, even if we need to grab something from online.

**Comment by willmurphyscode** [comment]
>  I'm also curious if there is other information that is not in the grype document today that would be useful, even if we need to grab something from online.

I think @spiffcs mentioned that "how long ago was this CVE published?" is a frequent request. Maybe we could add that?

**Comment by willmurphyscode** [comment]
Here's some prototype output I'd like feedback on (note that the CVE is a known false positive in this case):

```
❯ go run main.go explain --cve CVE-2017-1000034 < willtmp/grype1164.json
CVE-2017-1000034 (High) for namespace "nvd:cpe":
Akka versions <=2.4.16 and 2.5-M1 are vulnerable to a java deserialization attack in its Remoting component resulting in remote code execution in the context of the ActorSystem.
Version Constraint: <= 2.4.16 || = 2.5 (unknown)
    matched artifacts: 
        package: Akka, aritfact ID: 2a2d008f3f147fb, version: 1.5.0
            PURL: pkg:nuget/Akka@1.5.0
            CPE match on `cpe:2.3:a:akka:akka:*:*:*:*:*:*:*:*`
            Locations: 
                - /root/.dotnet/tools/.store/pbm/1.3.0/pbm/1.3.0/tools/net6.0/any/pbm.deps.json
        package: Akka, aritfact ID: d23259f9b42f40c1, version: 1.5.0
            PURL: pkg:nuget/Akka@1.5.0
            CPE match on `cpe:2.3:a:akka:akka:*:*:*:*:*:*:*:*`
            Locations: 
                - /root/.dotnet/tools/.store/pbm/1.3.0/pbm/1.3.0/tools/netcoreapp3.1/any/pbm.deps.json
        package: Akka, aritfact ID: b46d423045155de2, version: 1.5.0
            PURL: pkg:nuget/Akka@1.5.0
            CPE match on `cpe:2.3:a:akka:akka:*:*:*:*:*:*:*:*`
            Locations: 
                - /root/.dotnet/tools/.store/pbm/1.3.0/pbm/1.3.0/tools/net7.0/any/pbm.deps.json
        package: Akka, aritfact ID: 6fcc2fd328c85039, version: 1.5.2
            PURL: pkg:nuget/Akka@1.5.2
            CPE match on `cpe:2.3:a:akka:akka:*:*:*:*:*:*:*:*`
            Locations: 
                - /app/Lighthouse.deps.json
    URLs:  
        - https://nvd.nist.gov/vuln/detail/CVE-2017-1000034
        - http://doc.akka.io/docs/akka/2.4/security/2017-02-10-java-serialization.html
        - http://doc.akka.io/docs/akka/2.4/security/2017-02-10-java-serialization.html
        - http://doc.akka.io/docs/akka/2.4/security/2017-02-10-java-serialization.html
        - http://doc.akka.io/docs/akka/2.4/security/2017-02-10-java-serialization.html
```

Note that I'm wrapping CPE strings in backticks, because otherwise they turn into emoji and lose `*`s when pasted into GitHub, for example: cpe:2.3:a:akka:akka:*:*:*:*:*:*:*:*

**Comment by willmurphyscode** [comment]
Here's another example of the output:

```
CVE-2022-29458 (High) for namespace "debian:distro:debian:10":
ncurses 6.3 before patch 20220416 has an out-of-bounds read and segmentation violation in convert_strings in tinfo/read_entry.c in the terminfo library.
Version Constraint: < 6.1+20181013-2+deb10u3 (deb)
    matched artifacts: 
        package: libncursesw6, aritfact ID: 71854d05b1ca05ab, version: 6.1+20181013-2+deb10u2
            PURL: pkg:deb/debian/libncursesw6@6.1+20181013-2+deb10u2?arch=amd64&upstream=ncurses&distro=debian-10
            This CVE is reported against ncurses, the origin of this deb package.
            Locations: 
                - /usr/share/doc/libtinfo6/copyright
                - /var/lib/dpkg/info/libncursesw6:amd64.md5sums
                - /var/lib/dpkg/status
        package: libtinfo6, aritfact ID: 9e8c05e586cbb968, version: 6.1+20181013-2+deb10u2
            PURL: pkg:deb/debian/libtinfo6@6.1+20181013-2+deb10u2?arch=amd64&upstream=ncurses&distro=debian-10
            This CVE is reported against ncurses, the origin of this deb package.
            Locations: 
                - /usr/share/doc/libtinfo6/copyright
                - /var/lib/dpkg/info/libtinfo6:amd64.md5sums
                - /var/lib/dpkg/status
        package: ncurses-base, aritfact ID: a9450a198d2ae455, version: 6.1+20181013-2+deb10u2
            PURL: pkg:deb/debian/ncurses-base@6.1+20181013-2+deb10u2?arch=all&upstream=ncurses&distro=debian-10
            This CVE is reported against ncurses, the origin of this deb package.
            Locations: 
                - /usr/share/doc/ncurses-base/copyright
                - /var/lib/dpkg/info/ncurses-base.conffiles
                - /var/lib/dpkg/info/ncurses-base.md5sums
                - /var/lib/dpkg/status
        package: ncurses-bin, aritfact ID: 2d41aa0664b272f4, version: 6.1+20181013-2+deb10u2
            PURL: pkg:deb/debian/ncurses-bin@6.1+20181013-2+deb10u2?arch=amd64&upstream=ncurses&distro=debian-10
            This CVE is reported against ncurses, the origin of this deb package.
            Locations: 
                - /usr/share/doc/ncurses-bin/copyright
                - /var/lib/dpkg/info/ncurses-bin.md5sums
                - /var/lib/dpkg/status
    URLs:  
        - https://security-tracker.debian.org/tracker/CVE-2022-29458
        - https://security-tracker.debian.org/tracker/CVE-2022-29458
        - https://security-tracker.debian.org/tracker/CVE-2022-29458
        - https://security-tracker.debian.org/tracker/CVE-2022-29458
        - https://security-tracker.debian.org/tracker/CVE-2022-29458
```

It looks like the URLs need to get deduplicated, but I'm looking also for other feedback. Generating from the output of `grype -o json --platform linux/amd64 python:3.8.0-slim`.

**Comment by willmurphyscode** [comment]
Thanks for the feedback! The phrases like `This CVE is reported against ncurses, the origin of this deb package.` are meant to report both the match type and the source package. Only `exact-indirect-match` vulnerabilities do that; it displays the name of the vulnerable upstream package. Maybe the phrasing could be better? What could I say there that would make the nature of the match and the relationship between, for example, `libncursesw6` and `ncurses` more clear?

**Comment by westonsteimel** [comment]
Yeah, I think that makes it clearer.  Should probably also include something about version of the source package that was matched against as the source version isn't always the same as the package version.

**Comment by willmurphyscode** [comment]
After some feedback, here are two examples:

## Example including `exact-direct-match` and `exact-indirect-match`:

```
CVE-2022-0563 (Negligible) for namespace "debian:distro:debian:10":
A flaw was found in the util-linux chfn and chsh utilities when compiled with Readline support. The Readline library uses an "INPUTRC" environment variable to get a path to the library config file. When the library cannot parse the specified file, it prints an error message containing data from the file. This flaw allows an unprivileged user to read root-owned files, potentially leading to privilege escalation. This flaw affects util-linux versions prior to 2.37.4.
Version Constraint: none (deb)
    matched artifacts: 
        package: bsdutils, aritfact ID: 6a527d5438e6dfe9, version: 1:2.33.1-0.1
            PURL: pkg:deb/debian/bsdutils@1:2.33.1-0.1?arch=amd64&upstream=util-linux%402.33.1-0.1&distro=debian-10
            Indirect match on source package: This CVE is reported against util-linux (version 2.33.1-0.1), the origin of this deb package.
            Locations: 
                - /usr/share/doc/bsdutils/copyright
                - /var/lib/dpkg/info/bsdutils.md5sums
                - /var/lib/dpkg/status
        package: fdisk, aritfact ID: 8027c13b85becc7e, version: 2.33.1-0.1
            PURL: pkg:deb/debian/fdisk@2.33.1-0.1?arch=amd64&upstream=util-linux&distro=debian-10
            Indirect match on source package: This CVE is reported against util-linux (version 2.33.1-0.1), the origin of this deb package.
            Locations: 
                - /usr/share/doc/fdisk/copyright
                - /var/lib/dpkg/info/fdisk.md5sums
                - /var/lib/dpkg/status
        package: libblkid1, aritfact ID: ef0026c7016096be, version: 2.33.1-0.1
            PURL: pkg:deb/debian/libblkid1@2.33.1-0.1?arch=amd64&upstream=util-linux&distro=debian-10
            Indirect match on source package: This CVE is reported against util-linux (version 2.33.1-0.1), the origin of this deb package.
            Locations: 
                - /usr/share/doc/libblkid1/copyright
                - /var/lib/dpkg/info/libblkid1:amd64.md5sums
                - /var/lib/dpkg/status
        package: libfdisk1, aritfact ID: cb327f12c3e07fd3, version: 2.33.1-0.1
            PURL: pkg:deb/debian/libfdisk1@2.33.1-0.1?arch=amd64&upstream=util-linux&distro=debian-10
            Indirect match on source package: This CVE is reported against util-linux (version 2.33.1-0.1), the origin of this deb package.
            Locations: 
                - /usr/share/doc/libfdisk1/copyright
                - /var/lib/dpkg/info/libfdisk1:amd64.md5sums
                - /var/lib/dpkg/status
        package: libmount1, aritfact ID: 7bb879338410593f, version: 2.33.1-0.1
            PURL: pkg:deb/debian/libmount1@2.33.1-0.1?arch=amd64&upstream=util-linux&distro=debian-10
            Indirect match on source package: This CVE is reported against util-linux (version 2.33.1-0.1), the origin of this deb package.
            Locations: 
                - /usr/share/doc/libmount1/copyright
                - /var/lib/dpkg/info/libmount1:amd64.md5sums
                - /var/lib/dpkg/status
        package: libsmartcols1, aritfact ID: e8f40ceea382bf5f, version: 2.33.1-0.1
            PURL: pkg:deb/debian/libsmartcols1@2.33.1-0.1?arch=amd64&upstream=util-linux&distro=debian-10
            Indirect match on source package: This CVE is reported against util-linux (version 2.33.1-0.1), the origin of this deb package.
            Locations: 
                - /usr/share/doc/libsmartcols1/copyright
                - /var/lib/dpkg/info/libsmartcols1:amd64.md5sums
                - /var/lib/dpkg/status
        package: libuuid1, aritfact ID: e4afe23b51bfc2d7, version: 2.33.1-0.1
            PURL: pkg:deb/debian/libuuid1@2.33.1-0.1?arch=amd64&upstream=util-linux&distro=debian-10
            Indirect match on source package: This CVE is reported against util-linux (version 2.33.1-0.1), the origin of this deb package.
            Locations: 
                - /usr/share/doc/libuuid1/copyright
                - /var/lib/dpkg/info/libuuid1:amd64.md5sums
                - /var/lib/dpkg/status
        package: mount, aritfact ID: a4fdaf4147692a93, version: 2.33.1-0.1
            PURL: pkg:deb/debian/mount@2.33.1-0.1?arch=amd64&upstream=util-linux&distro=debian-10
            Indirect match on source package: This CVE is reported against util-linux (version 2.33.1-0.1), the origin of this deb package.
            Locations: 
                - /usr/share/doc/mount/copyright
                - /var/lib/dpkg/info/mount.md5sums
                - /var/lib/dpkg/status
        package: util-linux, aritfact ID: a8f56fdef076280b, version: 2.33.1-0.1
            PURL: pkg:deb/debian/util-linux@2.33.1-0.1?arch=amd64&distro=debian-10
            Locations: 
                - /usr/share/doc/util-linux/copyright
                - /var/lib/dpkg/info/util-linux.conffiles
                - /var/lib/dpkg/info/util-linux.md5sums
                - /var/lib/dpkg/status
    URLs:  
        - https://security-tracker.debian.org/tracker/CVE-2022-0563
```

## Example of CPE match

(note that in this case the match is known to be a false positive)

```
CVE-2017-1000034 (High) for namespace "nvd:cpe":
Akka versions <=2.4.16 and 2.5-M1 are vulnerable to a java deserialization attack in its Remoting component resulting in remote code execution in the context of the ActorSystem.
Version Constraint: <= 2.4.16 || = 2.5 (unknown)
    matched artifacts: 
        package: Akka, aritfact ID: 2a2d008f3f147fb, version: 1.5.0
            PURL: pkg:nuget/Akka@1.5.0
            CPE match on `cpe:2.3:a:akka:akka:*:*:*:*:*:*:*:*`
            Locations: 
                - /root/.dotnet/tools/.store/pbm/1.3.0/pbm/1.3.0/tools/net6.0/any/pbm.deps.json
        package: Akka, aritfact ID: d23259f9b42f40c1, version: 1.5.0
            PURL: pkg:nuget/Akka@1.5.0
            CPE match on `cpe:2.3:a:akka:akka:*:*:*:*:*:*:*:*`
            Locations: 
                - /root/.dotnet/tools/.store/pbm/1.3.0/pbm/1.3.0/tools/netcoreapp3.1/any/pbm.deps.json
        package: Akka, aritfact ID: b46d423045155de2, version: 1.5.0
            PURL: pkg:nuget/Akka@1.5.0
            CPE match on `cpe:2.3:a:akka:akka:*:*:*:*:*:*:*:*`
            Locations: 
                - /root/.dotnet/tools/.store/pbm/1.3.0/pbm/1.3.0/tools/net7.0/any/pbm.deps.json
        package: Akka, aritfact ID: 6fcc2fd328c85039, version: 1.5.2
            PURL: pkg:nuget/Akka@1.5.2
            CPE match on `cpe:2.3:a:akka:akka:*:*:*:*:*:*:*:*`
            Locations: 
                - /app/Lighthouse.deps.json
    URLs:  
        - https://nvd.nist.gov/vuln/detail/CVE-2017-1000034
        - http://doc.akka.io/docs/akka/2.4/security/2017-02-10-java-serialization.html
```

It's worth pointing out in the second case that we have obviously violated the version constraints when CPE matching.

I'm looking for feedback on two dimensions:

1. Is this enough examples to evaluate the feature, or is there type of CVE or situation that should also be included?
2. Is the information presented clear and complete enough to send a pull request? (I don't want to build a bunch of unit tests, fight the linter, etc, just to change the format completely later, so hoping for a review on the above _output_ before opening a PR.)
