### ISSUE TITLE
Expand the list of criteria supported by ignore rules

### ISSUE THREAD

**Issue by mirekphd** [anchore/grype#1580]
**What would you like to be added**:
* add **container name** (tagged and not) as well as **severity level** (plus any other criteria that you may still consider useful here) to 
expand the list of criteria supported by ignore rules ([specifying-matches-to-ignore](https://github.com/anchore/grype/blob/main/README.md#specifying-matches-to-ignore)) (e,g.:
``` 
  - package:
      severity: Critical
  - container:
      legacy:20010911
```
* add support for lists, especially for package name (e.g.:
```
- package:
    name: [commons-text, duke, hadoop-annotations, hadoop-auth, hadoop-aws, hadoop-common, hadoop-hdfs-client, jackson-databind, java-xmlbuilder, log4j, nimbus-jose-jwt]
- package:
    severity: [Critical, High, Medium, Low]
```

**Why is this needed**:
* allow more precise control of false negatives / wont-fix cases, for more fine-grained / precise scanning and more customized reporting 

**Additional context**:

A good test container for this is an one with a long and varied list of vulnerabilities, some of which cannot be fixed due to their integration with upgrade-resistant legacy systems.

**Comment by tgerla** [comment]
Hi @mirekphd, in general we would suggest ignoring specific vulnerabilities by CVE or GHSA ID to solve the problem of upgrade-resistant legacy systems, but we can definitely discuss more features like this. But we wanted to make sure you knew that you could list multiple package names like this:

```yaml
ignore:
    - package:
      name: libcurl
    - package:
      name: second-package
```

Would this at least satisfy your request for a list of package names?

If you can share any more specifics about your use case for ignoring severities and entire container images, we would appreciate it. I'm not sure we fully understand what you need here. Thanks!
