### ISSUE TITLE
Conflicting config defaults

### ISSUE THREAD

**Issue by benjaminwilcox** [anchore/grype#2239]
This blog post from Anchore states to stop matching with CPEs: https://anchore.com/blog/say-goodbye-to-false-positives/

However the [default configuration settings](https://github.com/anchore/grype#configuration) set: 
```
    # even if CPE matching is disabled, make an exception when scanning for "stdlib".
    always-use-cpe-for-stdlib: true
```
and
```
  stock:
    using-cpes: true
```

Am I missing something here?

**Comment by spiffcs** [comment]
👋 Thanks for the issue @benjaminwilcox - This is probably on us to update the documentation to be a bit clearer, but for now here is a quick explanation.

Both of these config values live within the larger `match` section of the grype config.

The first config value you listed `always-use-cpe-for-stdlib: true` applies only to the Golang standard library package. This means that when grype encounters the `stdlib` package picked up by syft's golang cataloger it will use CPEs as the match basis. This is different from the default behavior of grype which as you said uses PURLs when available from the GHSA database. The reason for this is that the golang `stdlib` vulnerabilities are not reported on GHSA.

The second config value dictates when cpes are being used when a package is not part of a more specific ecosystem
```
match:
  java:
    # use CPE matching to find vulnerabilities (env: GRYPE_MATCH_JAVA_USING_CPES)
    using-cpes: false

  jvm:
    # (env: GRYPE_MATCH_JVM_USING_CPES)
    using-cpes: true

  dotnet:
    # use CPE matching to find vulnerabilities (env: GRYPE_MATCH_DOTNET_USING_CPES)
    using-cpes: false

  golang:
    # use CPE matching to find vulnerabilities (env: GRYPE_MATCH_GOLANG_USING_CPES)
    using-cpes: false

    # use CPE matching to find vulnerabilities for the Go standard library (env: GRYPE_MATCH_GOLANG_ALWAYS_USE_CPE_FOR_STDLIB)
    always-use-cpe-for-stdlib: true

    # allow comparison between main module pseudo-versions (e.g. v0.0.0-20240413-2b432cf643...) (env: GRYPE_MATCH_GOLANG_ALLOW_MAIN_MODULE_PSEUDO_VERSION_COMPARISON)
    allow-main-module-pseudo-version-comparison: false

  javascript:
    # use CPE matching to find vulnerabilities (env: GRYPE_MATCH_JAVASCRIPT_USING_CPES)
    using-cpes: false

  python:
    # use CPE matching to find vulnerabilities (env: GRYPE_MATCH_PYTHON_USING_CPES)
    using-cpes: false

  ruby:
    # use CPE matching to find vulnerabilities (env: GRYPE_MATCH_RUBY_USING_CPES)
    using-cpes: false

  rust:
    # use CPE matching to find vulnerabilities (env: GRYPE_MATCH_RUST_USING_CPES)
    using-cpes: false

  stock:
    # use CPE matching to find vulnerabilities (env: GRYPE_MATCH_STOCK_USING_CPES)
    using-cpes: true
```

The stock section at the bottom of this config section tells grype to use cpe matching as a fallback for the case when a package is not part of a more specific ecosystem. An example of this kind of package would be when syft finds a binary package NOT part of an OS package manager package. 

So in short, grype's default behavior is to fallback to cpes for particular packages when there isn't a better upstream datasource.
