### ISSUE TITLE
Specifying matches to ignore not working when vulnerability id is passed

### ISSUE THREAD

**Issue by Gaurav2Github** [anchore/grype#2559]
**What happened**:
When scanning a directory  for vulnerabilities with Grype.
Under Grype configuration file, when specifying matches to ignore. It does not work for vulnerability ID (e.g. "CVE-2021-3828" or "GHSA-xmvv-w44w-j8wx")
```
# .grype.yml
# not working (with or without package details)

ignore:
  # full set of supported rule fields avalilable here:
  # https://github.com/anchore/grype?tab=readme-ov-file#specifying-matches-to-ignore
  - vulnerability: "CVE-2021-3828"
    fix-state: unknown
    package:
      name: mattermost-desktop          
      type: npm

```

Grype tool is only able to ignore when specifying the package name (e.g. "libcurl") under Grype configuration file.

```
# .grype.yml
# working

ignore:
  # full set of supported rule fields avalilable here:
  # https://github.com/anchore/grype?tab=readme-ov-file#specifying-matches-to-ignore
  - package:
      name: mattermost-desktop          
      type: npm
```
Grype installed version is 0.89.0

**What you expected to happen**:

It should work for vulnerability ID (e.g. "CVE-2021-3828" or "GHSA-xmvv-w44w-j8wx")
```
# .grype.yml
# Expect this working too (with or without package details)

ignore:
  # full set of supported rule fields avalilable here:
  # https://github.com/anchore/grype?tab=readme-ov-file#specifying-matches-to-ignore
  - vulnerability: "CVE-2021-3828"
    fix-state: unknown
    package:
      name: mattermost-desktop          
      type: npm

```

**How to reproduce it (as minimally and precisely as possible)**:

1. Link to GitHub public repo that we can try scanning https://github.com/microsoft/Web-Dev-For-Beginners
2. Clone the repo to local `path/to/Web-Dev-For-Beginners`
3. Run scan for vulnerabilities with Grype.
```
grype -f medium dir:path/to/Web-Dev-For-Beginners
```
4. Try to suppress one of the findings using grype configuration file
```
# .grype.yml
# Expect this working too (with or without package details)

ignore:
  # full set of supported rule fields avalilable here:
  # https://github.com/anchore/grype?tab=readme-ov-file#specifying-matches-to-ignore
  - vulnerability: "GHSA-jr5f-v2jv-69x6" #using github advisory id
    fix-state: unknown
    package:
      name: axios
      type: npm


ignore:
  # full set of supported rule fields avalilable here:
  # https://github.com/anchore/grype?tab=readme-ov-file#specifying-matches-to-ignore

  - vulnerability: "CVE-2025-27152" #using CVE id
    fix-state: unknown
    package:
      name: axios
      type: npm



```
5. Rerun scan for vulnerabilities with Grype.
```
grype -f medium dir:path/to/Web-Dev-For-Beginners

# Expect the finding to be ignored.  but that not the case right now.
```

7. Try to suppress one of the findings using grype configuration file using package name alone
```
# .grype.yml
# Expect this working too (with or without package details)

ignore:
  # full set of supported rule fields avalilable here:
  # https://github.com/anchore/grype?tab=readme-ov-file#specifying-matches-to-ignore
  - package:
      name: axios
      type: npm

```
8. Rerun scan for vulnerabilities with Grype.
```
grype -f medium dir:path/to/Web-Dev-For-Beginners

# Expect the finding to be ignored.  And that's the case.
```
**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:  0.89.0
- OS (e.g: `cat /etc/os-release` or similar): 24.04 LTS (Noble Numbat)

**Comment by kzantow** [comment]
Hi @Gaurav2Github -- it looks like you were specifying `fix-state: unknown`, but this vulnerability has a fix state of fixed. If you remove that line, it works as you expect. In other words, these configurations work:
```
  - vulnerability: "GHSA-jr5f-v2jv-69x6" # using github advisory id
    package:
      name: axios
      type: npm
```
```
  - vulnerability: "CVE-2025-27152" # when using --by-cve
    package:
      name: axios
      type: npm
```

Also: so you understand what it's going to ignore: if there is a GHSA match, you will need to use the GHSA vulnerability ID, not the CVE, unless you use the `--by-cve` option, in which case the CVE will work to ignore direct CVE matches and GHSA matches with the associated CVE.

If I'm missing something please let me know.
