### ISSUE TITLE
Grype false positive for Github Actions using hashes for versions

### ISSUE THREAD

**Issue by dannystaple** [anchore/grype#2606]
**What happened**:

GitHub workflows are configured using immutable hashes for an action instead of just a version number:
```yaml
uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
```

Grype then reports multiple vulnerabilities associated with earlier versions:

```
  NAME                      INSTALLED                                 FIXED-IN  TYPE           VULNERABILITY        SEVERITY 
  tj-actions/changed-files  ed68ef82c095e0d48ec87eccea555d944a631a4c  41        github-action  GHSA-mcph-m25j-8j63  High      
  tj-actions/changed-files  ed68ef82c095e0d48ec87eccea555d944a631a4c  46.0.1    github-action  GHSA-mrrh-fwg8-r2c3  High
  [0043] ERROR discovered vulnerabilities at or above the severity threshold
```

**What you expected to happen**:

Grype would consider the hash, or pick up the commented version.

**How to reproduce it (as minimally and precisely as possible)**:

- Swap a Github action version reference for a SHA reference with a comment. The tj-actions/changed-files is a great example.
- Run Grype.

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by dannystaple** [comment]
Can also be reproduced in 0.91.0, using the docker image:
```bash
$ docker run -v${PWD}:${PWD} anchore/grype:v0.91.0 ${PWD}
[0000]  WARN no explicit name and version provided for directory source, deriving artifact ID from the given path (which is not ideal)
NAME                      INSTALLED                                 FIXED-IN  TYPE           VULNERABILITY        SEVERITY 
tj-actions/changed-files  ed68ef82c095e0d48ec87eccea555d944a631a4c  41        github-action  GHSA-mcph-m25j-8j63  High      
tj-actions/changed-files  ed68ef82c095e0d48ec87eccea555d944a631a4c  46.0.1    github-action  GHSA-mrrh-fwg8-r2c3  High
```

**Comment by popey** [comment]
Related: https://github.com/anchore/grype/issues/1503

**Comment by spiffcs** [comment]
Just tested this as well and wanted to note that we are NOT parsing strings like `v46` as is showing in the tj actions documentation here:
```
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      # -----------------------------------------------------------------------------------------------------------
      # Example 1
      # -----------------------------------------------------------------------------------------------------------
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
```

We would need this to be a proper semver `v46.0.0` for it to be entered into the SBOM. I think there is a small bug fix here where we can make the semver parsing a little more generous.

I otherwise tested this just now with a `syft -o json dir:. | grype` which had an affected `.github` directory using the actions and a proper commented semver. It showed both vulnerabilities
