### ISSUE TITLE
Expiry date for ignore rules

### ISSUE THREAD

**Issue by rmkanda** [anchore/grype#452]
**What would you like to be added**:
Adding an optional expiry date for the ignore rules

**Why is this needed**:
For example, there is a vulnerability on a package and it is valid. but the team needs a week to fix it. In those situations, we can have an expiry date for the ignore rules - so that it alerts again if the issue is not fixed.

**Example**
```
ignore:
   - vulnerability: CVE-2008-4318
      expiry: 2021-12-30 01:00:00 UTC
```

**Comment by JipSogeti** [comment]
This would help me migrate from Trivy and OWASP Dependency Check to grype (both of them support CVE expiry rules).

**Comment by kzantow** [comment]
#1148 mentioned a slightly different naming suggestion:
```
ignore:
  # This is the full set of supported rule fields:
  - vulnerability: CVE-2008-4318
    fix-state: unknown
    valid-until: 03-03-2023      <---- new field for time-limit
    package:
      name: libcurl
      version: 1.5.1
      type: npm
```
