### ISSUE TITLE
npm false positive CVEs

### ISSUE THREAD

**Issue by thediveo** [anchore/grype#496]
More false positives turned up in the web UI part of my [lxkns](https://github.com/thediveo/lxkns) project.

```yaml
ignore:
    # Barking up the wrong tree...
    - vulnerability: CVE-2009-4590 # php, not npm package
      package:
        type: npm
    - vulnerability: CVE-2009-4591 # sql engine, not npm package
      package:
        type: npm
    - vulnerability: CVE-2009-4592 # php, not npm package
      package:
        type: npm
    - vulnerability: CVE-2011-0220 # apfel bonjour, not npm package
      package:
        type: npm
    - vulnerability: CVE-2013-1779 # drupal, not npm package
      package:
        type: npm
    - vulnerability: CVE-2014-2980 # gnustep, not npm package
      package:
        type: npm
    - vulnerability: CVE-2017-18589 # rust, not npm package
      package:
        type: npm
    - vulnerability: CVE-2020-7663 # ruby, not npm package
      package:
        type: npm
    - vulnerability: CVE-2020-7753 # component/trim, not Trott/trim
      package:
        type: npm
```
