### ISSUE TITLE
Flag to disable db check and update

### ISSUE THREAD

**Issue by willyw0nka** [anchore/grype#878]
**What would you like to be added**:
A flag to disable the process of checking if there is a newer db and updating the db

**Why is this needed**:
There are certain scenarios where you want to sacrifice a bit of security in exchange of speed. Scanning lots of images in a row or machines with slow Internet connection/poor resources are a couple of them. In both scenarios you can run `grype db update` and then all the scans you want to ensure you are not getting false negatives.

**Additional context**:
This flag could be `grype anchore/grype --update-db=false` or `grype anchore/grype --no-update-db`

**Comment by willyw0nka** [comment]
UPDATE:
the equivalent of 
```yaml
db:
  # check for database updates on execution
  # same as GRYPE_DB_AUTO_UPDATE env var
  auto-update: true
```
in the config file or environment variable but as a cli flag. Is there any reason this config has not been ported to a cli flag?
